# Introduction to Eigenvalue and Eigenvector

A matrix eigenvalue problem considers the vector equation in the following picture

Here A is a given square matrix, an unknown scalar $\lambda$, and x an unknown vector.

In a matrix eigenvalue problem, the task is to determine $\lambda$’s and x’s that satisfy the equation below. 

Since x = 0 is always a solution for any $\lambda$ and thus not interesting, we only admit solutions with $x \neq 0$

The solutions to the equation are given the following names: 


Eigenvalues of A : The $\lambda$’s that satisfy the equation 

Eigenvectors of A: The corresponding nonzero x’s that also satisfy the equation


![vector equation](img/vectorequation.png)

# Example of Eigenvalue and Eigenvector

### The right-hand side in the following figure shows an example for a matrix with a pair of eigenvalue (i.e. 10) and eigenvector (i.e. [3,4])

### The matrix multiplication on the left handside show that there is no eigenvalue nor eigenvector formed



![Example of eigenvalue and eigenvector](img/exampleofeigenvalue.png)

In [1]:
import numpy as np
from scipy import linalg

A = np.array([[6,3],[4,7]])
la, v = linalg.eig(A) 

l1, l2 = la 
v1 = v[:,0] 
v2 = v[:,1] 

print(A)

# first possible pair of eigenvalue and eigenvector
print(l1)
print(v1)

# second possible pair of eigenvalue and eigenvector
print(l2)
print(v2)

[[6 3]
 [4 7]]
(3+0j)
[-0.70710678  0.70710678]
(10+0j)
[-0.6 -0.8]


# Mathematics for multiple eigenvalues and its corresponding eigenvector

We see that for a given square matrix A, we are finding $\lambda$ as the eigenvalue and its corresponding eigenvector that can satisfy the equation. Let's see the mathematical operation below


![Step 1 of eigenvalue calculation](img/mathofeigenvalue.png)

![Step 2 of eigenvalue calculation](img/mathofeigenvalue3.png)

![Step 3 of eigenvalue calculation](img/mathofeigenvalue2.png)

# Application of Eigenvalues: Problems Arising from Population Models. Leslie Model

The Leslie model describes age-specified population growth, as follows. Let the oldest age attained by the females in some animal population be 9 years. Divide the population into three age classes of 3 years each. Let the “Leslie matrix” as below 



![Leslie Matrix as the square matrix for finding eigenvalue](img/lesilemodel.png)

In [19]:
import numpy as np
from scipy import linalg

l = np.array([[0,2.3,0.4],[0.6,0,0],[0,0.3,0]])

la, v = linalg.eig(l) 


In [4]:
import numpy as np

l = np.array( [[0,2.3,0.4], [0.6, 0, 0],[0,0.3,0]])
p = np.array([[400],[400],[400]])

p_new = l @ p
print(p_new)

[[1080.]
 [ 240.]
 [ 120.]]


In [6]:
b = np.array([400,400,400])
l @ b

array([1080.,  240.,  120.])

In [20]:
l1, l2, l3 = la 
v1 = v[:,0] 
v2 = v[:,1] 
v3 = v[:,2] 

print(l)

# first possible pair of eigenvalue and eigenvector
print(l1)
print(v1)

# second possible pair of eigenvalue and eigenvector
print(l2)
print(v2)

# second possible pair of eigenvalue and eigenvector
print(l3)
print(v3)


[[0.  2.3 0.4]
 [0.6 0.  0. ]
 [0.  0.3 0. ]]
(1.2000000000000002+0j)
[-0.88888889 -0.44444444 -0.11111111]
(-1.1477225575051662+0j)
[ 0.87978097 -0.45992699  0.12021903]
(-0.052277442494833896+0j)
[ 0.01495588 -0.17165196  0.98504412]


![solution](img/lesliesolution.png)