In [8]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.random_uniform((3,3),minval = 0, maxval =1, seed =420)
b = tf.eye(3,3)
mult_op = a * b

In [3]:
with tf.Session() as sess:
    result = sess.run(mult_op)
    print(result)

[[0.98712194 0.         0.        ]
 [0.         0.23336256 0.        ]
 [0.         0.         0.9412434 ]]


## Using Placeholder

In [10]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [13]:
c = np.eye(3,3)
d = np.random.randint(0,100, (3,3))

In [33]:
new_mop = x * y

with tf.Session() as sess:
    result = sess.run( new_mop, feed_dict = {x : c, y: d})
    print(result)

[[11.  0.  0.]
 [ 0.  3.  0.]
 [ 0.  0. 45.]]


### Using Variables now

In [38]:
init = tf.global_variables_initializer()

my_place = tf.placeholder(tf.float32)
my_mat = tf.Variable(tf.ones((1,3)))
act_fun = tf.sigmoid( result  )

my_temp =  np.random.randint(0,10, size = (3,3))

In [39]:
with tf.Session() as sess:
    sess.run(init)
    result = sess.run( act_fun , feed_dict = {my_place : my_temp})
    print(result)

[[0.9999833  0.5        0.5       ]
 [0.5        0.95257413 0.5       ]
 [0.5        0.5        1.        ]]


## Exercise
* [quick draw data](https://quickdraw.withgoogle.com/data) or [here](https://github.com/wagenaartje/quickdraw.js/)