# Numpy exercises

In [2]:
import numpy as np

**1. Create a null vector of size 10**

In [7]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# %load solutions/np_1.py
Z = np.zeros(10)


**2. Create a null vector of size 10 but the fifth value which is 1**

In [12]:
a = (np.arange(10) == 4).astype('int')
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
# %load solutions/np_2.py
Z = np.zeros(10)
Z[5] = 1


**3.  Create a vector with values ranging from 10 to 49**

In [14]:
a =np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# %load solutions/np_3.py


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**4. Reverse a vector using slicing**

In [16]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
# %load solutions/np_4.py
Z = np.arange(50)
Z[::-1]


**5. Create a 3x3 matrix with values ranging from 0 to 8**

In [18]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# %load solutions/np_5.py


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**6. Create a 5x5 identity matrix**

In [38]:
a = np.zeros(25).reshape(5,5)
for idx in [ (i,i) for i in range(5)]:
    a[idx] = 1
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# %load solutions/np_6.py
Z = np.eye(5)


**7. Create a 5x5 array with random values and find the minimum and maximum values**

In [23]:
a = np.random.rand(25).reshape(5,5)
a

array([[0.78776622, 0.77169432, 0.87998922, 0.95762161, 0.09918729],
       [0.42761423, 0.02597275, 0.47089986, 0.30874272, 0.15917097],
       [0.14910639, 0.23244414, 0.28838552, 0.13612073, 0.07917514],
       [0.55715175, 0.77378338, 0.59948855, 0.93349453, 0.41283765],
       [0.59126842, 0.00515183, 0.37342564, 0.41190496, 0.56366276]])

In [25]:
print(f'Max: {a.max()}')
print(f'Min: {a.min()}')

Max: 0.957621610457882
Min: 0.005151825969245238


In [7]:
# %load solutions/np_7.py


0.9739941002794636
0.02421064278372298


**8. Create a random vector of size 10 and find the mean value**

In [26]:
np.random.rand(10).mean()

0.4898085824845239

In [14]:
# %load solutions/np_8.py


0.6188910110826079


** 9. Create a 2d array with 1 on the border and 0 inside**

In [35]:
a = np.zeros(100).reshape(10,10)
a[:, 0] = a[:,-1] = a[0, :] = a[-1, :] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# %load solutions/np_9.py
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

** 10. Normalize a 5x5 random matrix**

### JHO's Notes
On how to normalize [check][wiki_link]

[wiki_link]: https://en.wikipedia.org/wiki/Normalization_(statistics)

In [42]:
a = np.random.random((5,5))
(a - a.mean())/ a.std()

array([[ 0.19830915,  0.77376902,  1.36828781, -1.59889088, -0.85095448],
       [-1.52487408, -0.11190618,  0.0985019 , -0.51485133,  0.01598358],
       [-1.24473453,  1.55636583,  0.83483176, -1.65143603,  0.96103502],
       [ 0.3952648 ,  1.47617464,  0.52218675, -1.05907089,  1.09376799],
       [-0.74090394, -0.92887865,  1.3449185 , -0.35677441, -0.05612134]])

In [43]:
# %load solutions/np_10.py

array([[ 0.35350676, -0.77233622, -0.86071791, -0.9226958 , -0.68981236],
       [ 1.73371309,  1.73642272, -1.15957572, -0.89231387,  1.30014002],
       [-0.86039307, -0.18108705,  0.2166559 ,  1.5936547 , -0.31177812],
       [-0.37594304,  1.24989755, -0.76264252, -0.37402787, -0.4394691 ],
       [-0.95089273,  1.74454555,  1.10712898, -0.66458994, -0.81738995]])

**11. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

### JHO's Notes
A basic [tutorial](https://www.mathsisfun.com/algebra/matrix-multiplying.html) on Matrix Multiplication

In [50]:
a = np.ones(15).reshape(5,3)
b = np.array([ 3 for i in range(6)]).reshape(3,2)

In [51]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
b

array([[3, 3],
       [3, 3],
       [3, 3]])

In [53]:
np.dot(a,b)

array([[9., 9.],
       [9., 9.],
       [9., 9.],
       [9., 9.],
       [9., 9.]])

In [19]:
# %load solutions/np_11.py


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

** 12. Given a 1D array, negate all elements which are between 3 and 8, in place**

In [55]:
a = np.arange(11)
a[ (a >= 3) & (a <= 8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [ ]:
# %load solutions/np_12.py
Z = np.arange(11)
Z[3:9] = -Z[3:9]
Z

**13. How to find common values between two arrays? **

In [64]:
a = np.random.rand(10)* 10
b = np.random.rand(10)* 10
a = a.astype('int')
b = b.astype('int')
print(a)
print(b)
print( np.intersect1d(a,b) )

[6 0 5 5 4 2 6 3 5 5]
[0 8 7 1 2 5 8 2 7 6]
[0 2 5 6]


In [67]:
# %load solutions/np_13.py
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
Z1[Z1 == Z2]

print(Z1)
print(Z2)
print(Z1[Z1==Z2])

[7 2 0 8 4 2 2 3 4 5]
[2 2 5 9 0 6 4 6 1 8]
[2]


**14. How to get the dates of yesterday, today and tomorrow? **

### JHO's Note
NumPy got some cool [functionality in dates](https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.datetime.html) and [more](http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/arrays.datetime.html)

In [71]:
tmr = np.datetime64('today') + 2
yday = np.datetime64('today') -1
np.arange(yday, tmr)

array(['2018-10-23', '2018-10-24', '2018-10-25'], dtype='datetime64[D]')

2018-06-18 2018-06-19 2018-06-20


**15. Create a 5x5 matrix with row values ranging from 0 to 4 **

In [72]:
a = np.arange(5).reshape(1, 5)
b = np.ones(25).reshape(5,5)
b * a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [29]:
# %load solutions/np_15.py


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

**16. Create a random vector of size 10 and sort it**

In [74]:
a = np.random.random(10)
print(a)
print(np.sort(a))

[0.21779527 0.81563531 0.05055479 0.16760985 0.00530495 0.33805439
 0.92099475 0.37521898 0.19768365 0.69816308]
[0.00530495 0.05055479 0.16760985 0.19768365 0.21779527 0.33805439
 0.37521898 0.69816308 0.81563531 0.92099475]


In [34]:
# %load solutions/np_16.py


array([0.22217118, 0.24685862, 0.32945163, 0.45752506, 0.53290246,
       0.54520624, 0.8341904 , 0.84020095, 0.8474539 , 0.96333001])

**17. Consider two random array A and B, check if they are equal**

In [ ]:
# %load solutions/np_17.py
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
A == B

**18. Create random vector of size 10 and replace the maximum value by 0**

In [81]:
a = np.random.randint(0,10, 10)
print(a)
a[a.argmax()] = 0
print(a)

[5 8 9 5 2 7 7 9 1 8]
[5 8 0 5 2 7 7 9 1 8]


In [ ]:
# %load solutions/np_18.py
Z = np.random.random(10)
Z[Z.argmax()] = 0 

**19. How to convert a float (32 bits) array into an integer (32 bits) in place?**

### JHO's Note
This [link](https://stackoverflow.com/questions/4389517/in-place-type-conversion-of-a-numpy-array) might be useful

In [92]:
a = np.arange(10)
print(a.dtype)
a = a.astype('int32', copy = False)
print(a.dtype)

int64
int32


In [ ]:
# %load solutions/np_19.py
Z = np.arange(10, dtype=np.float32)
Z = Z.astype("int32")
Z

**20. Find the nearest value from a given value in an array**

In [105]:
a = np.random.randint(0,100, 10)
target = 50
b = abs(a - target)

print(a)
print(a[ b.argmin()])

[79 22 68 74 18  5 95 53 76 75]
53


In [ ]:
# %load solutions/np_20.py
Z = np.random.uniform(0,1,10) * 10
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

find_nearest(Z,5)

**21. How to get the diagonal of a dot product? **

In [124]:
a = np.arange(1,7).reshape(3,2)
b = np.repeat(1, 6).reshape(2,3)
c = np.dot(a,b)
eye = np.eye(3)

print(a)
print(c)
print( c[eye == 1])

[[1 2]
 [3 4]
 [5 6]]
[[ 3  3  3]
 [ 7  7  7]
 [11 11 11]]
[ 3  7 11]


### JHO's Note
the `@` is a matrix multiplication operator in Python 3.5
`np.diag` returns the diagional of a squared matrix 

In [ ]:
# %load solutions/np_21.py
A = np.random.uniform(0,1,(5,5))
np.diag(A @ A)

**22. How to swap two rows of an array? **

### JHO's Notes
The solution used [advanced slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing)

In [121]:
a = np.arange(25).reshape(5,5)
print(a)

b = a[1,:].copy()
a[1,:] = a[0,:]
a[0,:] = b

print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# %load solutions/np_22.py
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

For more exercises see [100 Numpy Exercies](https://github.com/rougier/numpy-100),