# Matrix 

A matrix is a grid of numbers arranged into m rows and n columns, kind of like a excel spread sheet or a pandas dataframe.

$$ A = 
\begin{bmatrix}
 1 & 2 \\ 
 3 & 4 \\ 
 5 & 6 
\end{bmatrix} $$


 $ A $ is a matrix with 3 row and 2 columns or a 3 by 2 matrix. The items inside a matrix are called elements, so each element in $ A $ is a number. In numpy there a numerous methods to create matrices, some are demonstrated bellow.


In [227]:
np.random.random((3,3))

array([[ 0.36592721,  0.70598879,  0.57818689],
       [ 0.24585161,  0.73850868,  0.33433893],
       [ 0.82485778,  0.92059805,  0.85819294]])

In [228]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [229]:
np.ones((2,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [230]:
np.eye(5) #

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [231]:
np.array([[1402,191],[1371,821],[949,1437]])

array([[1402,  191],
       [1371,  821],
       [ 949, 1437]])

## Matrix indexing

We can access individual elements using the syntax

```
Matrix[row,col]
```

In [232]:
A = np.array([[1402,191],[1371,821],[949,1437]])


1402

The normal python index rules apply so we can index matrix using 

```python
Matrix[start:stop:step,start:stop:step]
```

In [233]:
#A[0::2] #alternative syntax


array([[1402,  191],
       [ 949, 1437]])

In [232]:
A[1::2,:] # return only even rows

array([[1371,  821]])

In [233]:
A[0::2,0::2] # odd rows and odd cols

array([[1402],
       [ 949]])

## Matrix addition

When we you add two matrices the elements are added element wise. The same rules apply for subtraction

$$ \begin{bmatrix}
 1 & 2 \\ 
 3 & 4 \\ 
 5 & 6 
\end{bmatrix} +
 \begin{bmatrix}
 1 & 1 \\ 
 1 & 1 \\ 
 1 & 1 
\end{bmatrix} =
 \begin{bmatrix}
 1 +1 & 1 +2 \\ 
 1 + 3& 1 + 4 \\ 
 1 +5 & 1 + 6 
\end{bmatrix} $$

In traditional maths only matrices of the same size can be added or subtracted. However in numpy these rules are relax by something called broadcasting, which well cover later.

In [3]:
np.ones((5,5)) + np.ones((5,1)) 

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

## Multiplication 

Matrix multiplication is slghtly more complicated than addition and subtraction. I'll start by explaining when it's valid to multiply two matrices together and later how you do it.

### Inside outside rule

Matrix multiplication has different rules to addition and subtraction. Matrices must be of certain dimensions if we wish to multiply them together. Say we have matrix $ A $ which is **m by n** and we have matrix $ B $ which is **n by p**, the two matrices can only be multiplied if n ==  n. The resulting product will be **m by p**. This is explained by the picture bellow



![inny outey rule](https://www.freemathhelp.com/images/lessons/mat11.png)

We can express the above matrix multiplication in numpy like so.

In [234]:
X = np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [235]:
y = np.array([9,8,7])


array([9, 8, 7])

In [236]:
X*y

array([[ 9, 16, 21],
       [36, 40, 42]])

### The calculation

But how is the answers calculated? We can think of the calculation in terms of dot products.  We can figure out the resulting matrix shape using the inside out rule. So to fill position 1,1  in our new matrix we take the dot product from row 1 of the first matrix and column 1 from the second matrix

![matrix mul](https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg)

The next position we want to calculated is $ (1,2) $, so we take the dot product of row 1 from the first matrix and column two from the second. 

![](https://www.mathsisfun.com/algebra/images/matrix-multiply-b.svg)

## Reshaping

As we have seen above if matrices are not of the correct shape we can't do operations upon them. Often in deep learning we need to reshape matrices in order to create our networks. 

In [237]:
A = np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
A.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We can get the shape of a matrix like so.

In [154]:
C.shape

(4, 3)

In [155]:
B.shape

(2, 2)

## Order matters

The order of matrix multiplication matters. That means that

$$ AB \neq BA $$ 



In [2]:
A = np.arange(1,10).reshape((3,3))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
B = np.arange(10,19).reshape((3,3))


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
# np.matmul(A,B)


array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [8]:
B @ A

array([[138, 171, 204],
       [174, 216, 258],
       [210, 261, 312]])

In [9]:
A @ B  == B @ A #check eqaulity element wise

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [11]:
(A @ B  == B @ A).all() #Check if all of them are true

False

# Transpose

The transpose switches the rows and columns in a matrix.A transpose can be thought of as rotating a matrix around it's diagonal. The diagonal starts in the top left hand corner and ends in the bottom right and corner. In maths the transpose is indicated by a T in the top-right corner of the matrix.

$$ \begin{bmatrix}
 1 & 2 & 3 \\ 
 4 & 5 & 6
\end{bmatrix}^T =
\begin{bmatrix}
1 & 2\\ 
3 & 4\\ 
5 & 6
\end{bmatrix} $$

In [12]:
A = np.array([[1,0],[1,1]])


array([[1, 0],
       [1, 1]])

In [13]:
A.T

array([[1, 1],
       [0, 1]])

# Broadcasting

In numpy the rules for addition, subtraction and multiplication are relaxed. Broadcasting allows us to take the hadamard product (element wise multiplication) of a matrix and a vector, even though there shapes are not the same.



$$ \begin{bmatrix}
a_1  \\ 
a_2   
\end{bmatrix} \cdot
\begin{bmatrix}
b_1 & b_2  \\ 
b_3 & b_4   
\end{bmatrix} =
\begin{bmatrix}
a_1 \cdot b_1 & a_1 \cdot b_2  \\ 
a_2 \cdot b_3 &  a_2 \cdot b_4   
\end{bmatrix} $$

In [14]:
A = np.array([1,2])


array([[ 2,  6],
       [ 4, 10]])

The same rules apply for addition

In [15]:
A = np.array([0,1])


array([[1, 3],
       [3, 5]])

## Questions


** 1. **   Define a function that returns True of False depending if two matrices can be multiplied together.


In [19]:
import numpy as np
A = np.matrix([[1, 2], [3, 4]])
B = np.matrix([[1, 2, 5], [3, 4,10]])

print(A, A.shape)
print(B, B.shape)

def multiply_check(A,B):
    if A.shape[1] == B.shape[0]:
        return True
    else:
        return False
    
print(multiply_check(B,A))
print(multiply_check(A,B))

** 2. **  Define a function that given two matrices will return the dimension of the multiplication.

In [22]:
import numpy as np
A = np.matrix([[1, 2], [3, 4]])
B = np.matrix([[1, 2, 5], [3, 4,10]])

print(A, A.shape)
print(B, B.shape)

def multiply_dim(A,B):
    if A.shape[1] == B.shape[0]:
        C = np.dot(A,B)
        return C.shape
    else:
        return print("not multiplicable")
    
    
print(multiply_dim(B,A))
print(multiply_dim(A,B))

[[1 2]
 [3 4]] (2, 2)
[[ 1  2  5]
 [ 3  4 10]] (2, 3)
not multiplicable
None
(2, 3)


** 3. **  Create a 3 by 3 matrix with values ranging from 1 to 9

In [36]:
D = np.arange(1,10)
D = D.reshape(3,3)
D = np.asmatrix(D)
print(D, D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


### 4.

Create a 3 by 3 by 3 matrix with random values

In [38]:
D = np.random.random((3,3))
D = np.asmatrix(D)
print(D,D.shape)

[[0.13295292 0.17801839 0.71658803]
 [0.84763424 0.37530137 0.96930778]
 [0.44141777 0.09582032 0.89392722]] (3, 3)


### 5.

Reshape the following matrices $ A $ and $ B $ so that they can be multiplied together.

In [41]:
A = np.ones((3,4))
B = np.random.random((2,4))
print(A)
print(B.reshape(4,2))

np.dot(A,B.reshape(4,2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.93893704 0.08428479]
 [0.3368005  0.78531438]
 [0.89727584 0.00542449]
 [0.34873869 0.90782378]]


array([[2.52175207, 1.78284744],
       [2.52175207, 1.78284744],
       [2.52175207, 1.78284744]])

### 6.

Using C and D (defined bellow) perform the following operation $ C \cdot D^T $

In [43]:
C = np.ones((3,4))
D = np.random.random((2,4))

np.dot(C,D.T)

array([[2.54660101, 2.31224978],
       [2.54660101, 2.31224978],
       [2.54660101, 2.31224978]])

### 7. 
Given the bellow 3 matrices put them in a order that they can multiplied together

In [47]:
X1 = np.ones((4,3))
X2 = np.random.random((2,4))
X3 = np.random.random((3,4))

np.dot(np.dot(X2,X1),X3)


array([[1.76180747, 1.70349169, 1.75402308, 1.62013904],
       [3.51335743, 3.39706538, 3.49783396, 3.23084538]])

### 8.

How would you create a 8 by 8 matrix with a checkerboard pattern? * Hint * [::2] indexing will help. 

In [52]:
import numpy as np
print("Checkerboard pattern:")

x = np.zeros((8,8),dtype=int)
print(x)

x[1::2,::2] = 1
x[::2,1::2] = 1

print(x)

Checkerboard pattern:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 9.

Can you multiply the two matrices, $ A $ and $ B $, without using numpy?

In [75]:
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
print(result)

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


### 10. 

How would you take the transpose of a matrix without using numpy?

In [80]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
        result[j][i] = X[i][j]

print(X)
print("\n")
print(result)

[[12, 7], [4, 5], [3, 8]]


[[12, 4, 3], [7, 5, 8]]


## Additional resources

Bellow are list of useful resources

* [SciPy numpy talk](https://www.youtube.com/watch?v=lKcwuPnSHIQ)
* [Matrix multiplication ](https://www.freemathhelp.com/matrix-multiplication.html)
* [Maths needed for deep learning](https://www.quora.com/What-mathematical-background-does-one-need-for-learning-Deep-Learning)
* [Linear algebra for deep learning](http://www.deeplearningbook.org/contents/linear_algebra.html)
* [Great youtube playlist on linear algebra](https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw)
