# TensorFlow Basics

In [ ]:
import tensorflow as tf

In [ ]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

## Tensors

In [45]:
hello = tf.constant('Hello')

In [46]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [47]:
world = tf.constant('World')

In [48]:
result = hello + world

In [49]:
result

<tf.Tensor 'add_5:0' shape=() dtype=string>

In [50]:
type(result)

tensorflow.python.framework.ops.Tensor

In [51]:
# with opens and closes the session. 
# assign to result. 
with tf.Session() as sess:
    result = sess.run(hello+world)

In [52]:
# b representes byte literal - ignore it 
result

b'HelloWorld'

In [53]:
a = tf.constant(10)

In [54]:
b = tf.constant(20)

In [55]:
type(a)

tensorflow.python.framework.ops.Tensor

In [56]:
a + b

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [57]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [58]:
result

30

** Computations **

In [ ]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [ ]:
type(tensor_1)

In [ ]:
tensor_1 + tensor_2

In [ ]:
sess

In [ ]:
sess.close()

## Operations

In [59]:
const = tf.constant(10)

In [60]:
fill_mat = tf.fill((4,4),10)
fill_mat

<tf.Tensor 'Fill_2:0' shape=(4, 4) dtype=int32>

In [61]:
myzeros = tf.zeros((4,4))

In [62]:
myones = tf.ones((4,4))

In [ ]:
# normal distribution
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [ ]:
#random uniform distribution
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [63]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [64]:
# Only run this cell once!
sess = tf.InteractiveSession()

/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [65]:
# note - ops have eval method as well. typically we call sess.run
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 1.01556218  0.38395494  1.05763078 -0.6433894 ]
 [-0.33799961 -0.02702949 -1.13597298  0.43104345]
 [ 0.34710956  0.54177886 -0.1829899   0.41494504]
 [-0.65934581 -0.5508607  -0.26497412 -0.09637728]]


[[ 0.07711446  0.69631028  0.18820465  0.33810771]
 [ 0.03455591  0.35273433  0.11090505  0.54676902]
 [ 0.07443833  0.33321905  0.50237894  0.01221955]
 [ 0.74294257  0.01021922  0.82576203  0.29911244]]




## Matrix Multiplication

In [66]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [67]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [68]:
b = tf.constant([[10],[100]])

In [69]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [70]:
result = tf.matmul(a,b)

In [71]:
result.eval()

array([[210],
       [430]], dtype=int32)